### ISSUE TITLE
Slavic characters

### ISSUE THREAD

**Issue by markoboras0712** [thompsonsj/slate-serializers#105]
<img width="1226" alt="image" src="https://github.com/thompsonsj/slate-serializers/assets/75808588/45a3a812-5a97-4f1a-99f8-49c389c17d2b">

**Comment by thompsonsj** [comment]
I think I'll change the default config.

Default values:

```
encodeEntities: true,
alwaysEncodeBreakingEntities: false,
```

Under the hood, the serializer uses https://github.com/cheeriojs/dom-serializer which encodes entities by default.

I find myself using the following options with `slateToHtml`:

```
encodeEntities: false,
alwaysEncodeBreakingEntities: true,
```

...which will only encode entities such as `<` which would otherwise break the resulting HTML.

I find this a more sensible default, so will update this soon 👍  Thanks for the feedback.
