### ISSUE TITLE
Payload serializer - Internal link broken

### ISSUE THREAD

**Issue by frederico-taramaschi** [thompsonsj/slate-serializers#137]
It would seem that the serializer(payloadSlateToReactConfig) can no longer correctly set the href attribute on an internal link.
An internal link currently renders as follows `<a data-link-type="internal">xxx</a>`
External links stil work as expected `<a href="https://www.google.com/" data-link-type="custom">xxx</a>`

**Versions**
Payload: 2.3.1
Slate plugin: 1.2.1
slate-serializer: 2.1.6

**Comment by thompsonsj** [comment]
Hey! The problem is that there is no way to know how to create a `href` attribute value based on an internal link value in the Payload CMS Slate Rich Text Editor.

For this reason, I just added a `data-link-type="internal"` attribute/value.

The idea is that you can customise the config to provide your logic for translating internal links.

I've created an example of how to customise the config in https://github.com/thompsonsj/slate-serializers/pull/140. In this example, I use the `id` field from the document relationship on the internal link to generate a URL, but you can do anything here. For example, perhaps there's a `slug` field in your Payload CMS configuration?

Let me know if I can help further!
