### ISSUE TITLE
Missing LICENSE.md

### ISSUE THREAD

**Issue by popik34** [thompsonsj/slate-serializers#178]
Hello,

Could you please provide a license for this repository? We are interested in using your library; however, without a specified license, your code is not considered open source, and we cannot use it without your explicit approval. Was this omission intentional?

For more information, please refer to this discussion: https://github.com/orgs/community/discussions/82431

**Comment by Arcane36** [comment]
I am also interested in this. This project would hugely help me out, because I am implementing Payload CMS which uses slate, but has no out of the box solution for transforming slate json to html. And my client also needs a license to be specified.

**Comment by thompsonsj** [comment]
The omission was not intentional - added LICENSE.md in https://github.com/thompsonsj/slate-serializers/pull/179 👍 

Glad you are finding it useful! The whole project came from working in Payload CMS and realising that there was a lot to consider when serializing Slate to HTML and vice versa, so I am delighted others are finding it useful!
