### ISSUE TITLE
Line breaks to <br> tags (the opposite)

### ISSUE THREAD

**Issue by steven-prybylynskyi** [thompsonsj/slate-serializers#32]
Hey @thompsonsj thanks for initiative with the package!

We successfully able to convert html to slate, except the line breaks that are currently dismissed during conversion.

Here's a simple test that shows the issue.
![image](https://user-images.githubusercontent.com/3078595/214029568-560dc5e7-d75a-44d8-a4b7-a8b9b1bed186.png)

I don't see a similar to `htmlToSlate` config to convert those, e.g.

```
  /* Convert new line character (\n) to br tags */
  convertLineBreakToBr?: boolean
```

Is it available in a feature branch or it's just not addressed yet?

**Comment by steven-prybylynskyi** [comment]
Regarding [this part](https://github.com/thompsonsj/slate-serializers/blob/main/src/serializers/slatetoHtml/index.ts#L42), if the element is determined to be a value that implements the `Text` interface (meaning that it can contain only `text` field, isn't it?), is it still can be a 'pre' tag?

**Comment by steven-prybylynskyi** [comment]
@thompsonsj I've created a PR that addresses this with `convertLineBreakToBr` option, please review
https://github.com/thompsonsj/slate-serializers/pull/33/files

**Comment by thompsonsj** [comment]
> Regarding [this part](https://github.com/thompsonsj/slate-serializers/blob/v0.0.24/src/serializers/slatetoHtml/index.ts#L42), if the element is determined to be a value that implements the `Text` interface (meaning that it can contain only `text` field, isn't it?), is it still can be a 'pre' tag?

This confuses me as well when I revisit it 😅 .  I find `code` and `pre` tags a bit of a headache!

As you noted, for `slateToHtml` I translate any nodes marked with the `code: true` attributes to `<pre><code>...</code></pre>`. The code you reference is reading a Slate text node.

...and the other way around for `htmlToSlate`, I even go so far as to use regular expressions to reduce any `<pre>` and `<code>` HTML element tags down to a single `<code>` tag in order to make the conversion to Slate easier. The rationale for that is in https://github.com/thompsonsj/slate-serializers/blob/main/docs/config/htmlToSlate.md#htmlpreprocessstring.

It's good to know I'm not the only one that struggles with this! I had some helpful comments from @tiberiuichim early on who has also worked on a deserializer, and I noted similar struggles with handling `pre` and `code`: https://github.com/plone/volto/blob/4e619b73bda70c4b0e52a2fb48048bc11e6f0484/packages/volto-slate/src/editor/deserialize.js#L158-L161.

Long answer! But good for my own reference, I should revisit this at some point.

**Comment by steven-prybylynskyi** [comment]
Yeah @thompsonsj, as good as Slate is, you can still spend weeks if not months on serialization, which feels like the most tricky part.

In our case, we need something that can replace our existing RTE. the two legacy editors `wysihtml5` (that is a jQuery lib) and `summernote`. Both work well with HTML and we need to replicate serialization/deserialization in Slate for both to render and save client's HTML code without any noticeable changes.

We are good as long as we do not break each others HTML. That's why it's better to introduce changes using more `options` when there's no other choice.
