### ISSUE TITLE
Image type is not supported

### ISSUE THREAD

**Issue by mirzakhalov** [thompsonsj/slate-serializers#35]
I am using Slate editor with image and when trying to convert slate state to HTML, I notice that image types (with a hyperlink) are not completely omitted in the output.

Is there any plan to support this in the future? If not, does anyone know a good alternative for this?

![Screen Shot 2023-01-24 at 4 26 44 PM](https://user-images.githubusercontent.com/26018417/214421727-d9f49e85-fefd-47a7-b5c0-557d94ff869d.png)

**Comment by thompsonsj** [comment]
Hey @mirzakhalov ! The problem is that the [Slate editor is schema-less](https://github.com/thompsonsj/slate-serializers#configuration) - so I can't really offer a default configuration that will work for everyone out-of-the-box.

Can you give more context on how you are using the Slate editor? Did you configure it yourself or is it in an existing package/system? I'm interested in creating configurations for particular systems to give that out-of-the-box support in some cases. e.g. I am actively developing a custom config for [Payload CMS](https://payloadcms.com/).

I can see you have a Slate node with an `image` type and a `url` property. So in your case, the following will probably work:

```ts
import { ChildNode, Element } from 'domhandler'
import { slateToHtml, slateToDomConfig } from 'slate-serializers'

const config = {
      ...slateToDomConfig,
      elementTransforms: {
        ...slateToDomConfig.elementTransforms,
        image: ({ node }: { node?: any }) => {
          return new Element('img', {
            src: node.url,
          })
        },
      },
    }

slateToHtml(slateObject, config)
```

I created a test to verify this in https://github.com/thompsonsj/slate-serializers/pull/36.
