### ISSUE TITLE
Can slate-serializers run in nodejs environment

### ISSUE THREAD

**Issue by ailuoku6** [thompsonsj/slate-serializers#56]

**Comment by thompsonsj** [comment]
Yes it can! In fact, the rationale for building it was to have a serializer that would work in Node.js and the browser. That's why it uses [htmlparser2](https://www.npmjs.com/package/htmlparser2) under the hood:  https://github.com/thompsonsj/slate-serializers/blob/main/docs/engineering.md#htmlparser2.
