### ISSUE TITLE
Font Styles don't get serialized.

### ISSUE THREAD

**Issue by smw-1211** [thompsonsj/slate-serializers#59]
@thompsonsj I thank you for this wonderful serializer package but I am facing an issue.

Once we apply styles to the text selected, font styles like fontsize, font family and color get added to that text but don't get serialized neither in Slate object nor HTML format.

Anyone who has faced this same issue?

**Comment by thompsonsj** [comment]
Hi @smw-1211 ! This is expected - there is no default treatment of `style` tags. Because Slate JS is schema-less, it is unlikely that this package will do what you want it to do out of the box. A similar issue: https://github.com/thompsonsj/slate-serializers/issues/35.

However, for this very reason, it is quite straightforward to add some config options that will handle your text styles!

Can you post an example of the Slate you want to transform to HTML? Happy to add tests that will show you what config to use to get this working!

**Comment by smw-1211** [comment]
Hi @thompsonsj 

I appreciate your immediate response!!

However, I won't be able to share the code snippet. But to answer your question, I have a slate object with style tag within it and want it to be transformed to HTML for which I was using this package.

![image](https://github.com/thompsonsj/slate-serializers/assets/61089886/a981e224-8249-4dbc-a0fa-f8a603b7a31c)

For example, in this image above, the current output using this serializer is:

![image](https://github.com/thompsonsj/slate-serializers/assets/61089886/5e999149-7fba-435b-8195-24b6505c9619)

If you see the style tag didn't get wrapped inside the paragraph tag. I was just concerned about this.

**Comment by thompsonsj** [comment]
Hey @smw-1211 ! I examined the example you sent and thought about how you could achieve this. As I mentioned, your Slate JS setup is likely to be different from others - so its necessary to customize the config in order to handle `style` objects.

I've added a suite of tests in https://github.com/thompsonsj/slate-serializers/pull/63 to demonstrate how you can do it 😄 

And you'll need the latest release if you want your transforms to apply to the `strong` tag - 0.1.0.

Finally, if this works for you, let me know and I'll take a look at the other way around - `htmlToSlate`.

**Comment by smw-1211** [comment]
Hi @thompsonsj 

I could not exactly understand how can I handle the style object. For a better understanding, I have an another code snippet of how I am using the slateToHtml default function of this package.

![image](https://github.com/thompsonsj/slate-serializers/assets/61089886/6ab98090-7aba-4b3e-9596-a0c23f5a857f)

For example: If the value is this:

![image](https://github.com/thompsonsj/slate-serializers/assets/61089886/e1e209d8-8a81-4968-88ae-a85cc81e8fdb)

I get serialized output as this:

![image](https://github.com/thompsonsj/slate-serializers/assets/61089886/fb2d0ab8-905d-423c-b902-9369772e2bcc)

If you see the subscript tag as well as content in style tag doesn't get serialized. That's what I want a solution for.

Can you tag an example as a comment which I can refer to handle style object and also the custom markup elements such as subscript and superscript.

It would be of great help :). Thanks!!

**Comment by thompsonsj** [comment]
Hey @smw-1211 ! Note that before trying the below, you'll need to update to version `0.2.0`. I made some more changes 😅 .

At the top of your file, you can import the config object that is used for `slateToHtml`.

```ts
import { slateToDomConfig } from 'slate-serializers'
```

Then you can customise this config to perform transforms on any Slate JSON configuration. For example, you could customise the config like this:

```
const config = {
  ...slateToDomConfig,
  markMap: {
    ...slateToDomConfig.markMap,
    subscript: ['sub'],
  },
  markTransforms: {
    ...slateToDomConfig.markTransforms,
    style: ({ node }: { node?: any }) => {
      return new Element('span', {
        ...(node.style?.fontSize && { style: `font-size:${node.style.fontSize};` }),
      })
    },
  },
}
```

To summarise the customisations:

- Make `slateToHtml` aware of a `subscript` Slate property, and transform it to the `<sub>` HTML element tag.
- Check for `style.fontSize` on Slate JSON child node and wrap the resulting HTML in a `span` tag with an inline `font-size` style.

With the above import and config, `slateToHtml(value, config)` will return the following:

```html
<p><span style="font-size:20px;"><strong><sub>Paragraph</sub></strong></span></p>
```

Note that if you want to transform any CSS styles that appear in the `style` property on the Slate JSON child node, then I can post that example here - I have a test that uses [postcss](https://www.npmjs.com/package/postcss) and [postcss-js](https://www.npmjs.com/package/postcss-js) to transform any CSS in JS to inline `style` in the HTML.

**Comment by smw-1211** [comment]
Hey @thompsonsj 

Thanks a ton!! 

Now it is pretty clear, and it would be great if you share that example to transform CSS styles that appear in the style property on the Slate JSON child node.

**Comment by bdeepu** [comment]
Thank you so much for this wonderful package @thompsonsj  :-)

By following this conversation, we can now successfully perform slateToHtml conversion, but the reverse conversion from **htmlToSlate** is still not working. As a result, we are unable to load and render the saved html data and return it to the editor for further editing. This is a critical capability because we have saved some formats but cannot open it in the editor to modify them.

Along with @smw-1211, we are also looking forward to hearing from you on this. 

Any quick update on this would be greatly appreciated.

Thanks again :-)

**Comment by thompsonsj** [comment]
@bdeepu @smw-1211 I'm working on this. I'll update here soon.

I also have a big refactor in progress that will make it easier for me to offer different serializers (e.g. React, Astro...etc). One of the different serializers I'd like to offer is one that supports style attributes both ways out of the box, as I think this is a common use case.

One question while I am working on it - are you relying only on adding `span` tags with `style` attributes or are you setting style attributes directly on the elements themselves - e.g. `p`?

**Comment by thompsonsj** [comment]
https://github.com/thompsonsj/slate-serializers/pull/80 gives an example of how to convert HTML to Slate with a style object. Let me know if it makes sense!

**Comment by bdeepu** [comment]
Hi @thompsonsj , Thank you for your prompt response.
Yes, we are applying style attributes to the element directly. We'll test the most recent update for the HTML to Slate translation and report back.

Thank you once again. :-)

**Comment by bdeepu** [comment]
Hi @thompsonsj , we tried the latest version but it is not working as expected.  
Below object is converted slate json, but when we are passing this data to slate same is not reflecting in slate editor. bold, italic tags are getting applied but style is not getting applied.

`[
    {
        "type": "p",
        "children": [
            {
                "text": "cxvcxv",
                "style": {
                    "fontFamily": "fantasy",
                    "color": "#1fa853"
                }
            }
        ]
    },
    {
        "type": "p",
        "children": [
            {
                "text": "xcvxcv",
                "style": {
                    "color": "#cc3838"
                },
                "bold": true
            }
        ]
    },
    {
        "type": "p",
        "children": [
            {
                "text": "xcvxv",
                "style": {
                    "fontSize": "64px",
                    "color": "#cc3838"
                },
                "bold": true
            }
        ]
    }
]`

Could you please take a look at this?

I really appreciate the time you put into this. Thanks!

**Comment by thompsonsj** [comment]
Hey @bdeepu ! Cool - looks like we are getting there 😅 

Do you have the original Slate JSON available? Then we can compare to the JSON you pasted above and see what is missing - maybe we need to do something special to give your Slate implementation the data structure that it wants.

**Comment by bdeepu** [comment]
Hi @thompsonsj, looks like we found the issue here. Slate expects 'paragraph' instead of 'p'. We are trying some code level workarounds to convert type: 'p' to type: 'paragraph'.
will keep you posted on the outcome.
Thanks again :-)
